name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-coveralls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            cmake \
            g++ \
            clang-format \
            lcov \
            python3-pip

      - name: Configure and build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make

      - name: Run tests
        run: |
          cd build
          ./runTests

      - name: Generate coverage report
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '*/usr/include/*' '*/googletest/*' '*/build/*' --output-file coverage.cleaned.info

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          pip install coveralls
          cd build
          coveralls --exclude "*/banking/CMakeLists.txt" \
                    --exclude "*/tests/*.cpp" \
                    --exclude "*/googletest/*" \
                    --exclude "*/build/*" \
                    --gcov-tool lcov \
                    -i coverage.cleaned.info
